### ISSUE TITLE
Cost?

### ISSUE THREAD

**Issue by xackery** [bquenin/interpreter#8]
Just curious how much is each request (or sets of request) end up costing for this? Are results cached? Looking at the viability in the long term

**Comment by bquenin** [comment]
Hey @xackery, it's a very good question.

From the Google Vision pricing page:

![image](https://user-images.githubusercontent.com/11057786/180665825-bf169cdf-3aff-4450-a8c9-1ac8363fb0b5.png)

And from the Google Translate pricing page:

![image](https://user-images.githubusercontent.com/11057786/180665920-21339510-a36c-4289-a207-0a3a0e057c9e.png)

So it's basically:
* $1.50 for 1000 screenshots 
* the first 500,000 characters (per month) are free. Then it's $20 per million characters.

If we're taking 1 screenshot every 5 seconds, and let's assume this screenshot contains 40 characters (this is a guesstimate), the cost per hour is approximately:
* For vision: (60\*60)/5 = 720 screenshots per hour, which cost 720\*$1.50/1000 = $1.08
* For translate: 720*20 = 14,400 characters per hour, so it would take approximately 34h to trigger the billing.

If we estimate that a jRPG could be 100h long, then the cost would be:
* for vision: 100*1.08 = $108
* for translate: 100*14,400 - 500,000 = 940,000 characters, which is 940'000*20/1000000 = $18.80

Grand total = $126.80 for 100 hours, so $1.26 an hour

This is definitely not cheap!

In order to lower the cost, a very simple cache mechanism is implemented on the text to translate (preventing to translate the same "block" of text twice) but this is not implemented for the OCR, which is the costly operation.

Since the OCR is the most expensive operation, having a local OCR engine would drop the cost to translation only. I've been looking at some option such as Tesseract (check #5).

**Comment by xackery** [comment]
Awesome thanks! Super helpful information.
